-- Color x Área -- generado por Relaciones > Exportar el 2026-10-02 19:08
INSERT INTO COLOR_AREAS (color, area) VALUES ('Aguapanelo', 'peletizado');
INSERT INTO COLOR_AREAS (color, area) VALUES ('Amarillo', 'sellado');
INSERT INTO COLOR_AREAS (color, area) VALUES ('Amarillo', 'rollo');
INSERT INTO COLOR_AREAS (color, area) VALUES ('Amarillo', 'extrusion');
INSERT INTO COLOR_AREAS (color, area) VALUES ('Amarillo', 'peletizado');
INSERT INTO COLOR_AREAS (color, area) VALUES ('Azul', 'sellado');
INSERT INTO COLOR_AREAS (color, area) VALUES ('Azul', 'rollo');
INSERT INTO COLOR_AREAS (color, area) VALUES ('Azul', 'extrusion');
INSERT INTO COLOR_AREAS (color, area) VALUES ('Azul', 'peletizado');
INSERT INTO COLOR_AREAS (color, area) VALUES ('Beige', 'sellado');
INSERT INTO COLOR_AREAS (color, area) VALUES ('Beige', 'rollo');
INSERT INTO COLOR_AREAS (color, area) VALUES ('Beige', 'extrusion');
INSERT INTO COLOR_AREAS (color, area) VALUES ('Blanco', 'sellado');
INSERT INTO COLOR_AREAS (color, area) VALUES ('Blanco', 'rollo');
INSERT INTO COLOR_AREAS (color, area) VALUES ('Blanco', 'extrusion');
INSERT INTO COLOR_AREAS (color, area) VALUES ('Blanco', 'peletizado');
INSERT INTO COLOR_AREAS (color, area) VALUES ('Ladrillo', 'sellado');
INSERT INTO COLOR_AREAS (color, area) VALUES ('Ladrillo', 'rollo');
INSERT INTO COLOR_AREAS (color, area) VALUES ('Ladrillo', 'extrusion');
INSERT INTO COLOR_AREAS (color, area) VALUES ('Ladrillo', 'peletizado');
INSERT INTO COLOR_AREAS (color, area) VALUES ('Marrón', 'sellado');
INSERT INTO COLOR_AREAS (color, area) VALUES ('Marrón', 'rollo');
INSERT INTO COLOR_AREAS (color, area) VALUES ('Marrón', 'extrusion');
INSERT INTO COLOR_AREAS (color, area) VALUES ('Marrón', 'peletizado');
INSERT INTO COLOR_AREAS (color, area) VALUES ('Naranja', 'sellado');
INSERT INTO COLOR_AREAS (color, area) VALUES ('Naranja', 'rollo');
INSERT INTO COLOR_AREAS (color, area) VALUES ('Naranja', 'extrusion');
INSERT INTO COLOR_AREAS (color, area) VALUES ('Negro', 'sellado');
INSERT INTO COLOR_AREAS (color, area) VALUES ('Negro', 'rollo');
INSERT INTO COLOR_AREAS (color, area) VALUES ('Negro', 'extrusion');
INSERT INTO COLOR_AREAS (color, area) VALUES ('Negro', 'peletizado');
INSERT INTO COLOR_AREAS (color, area) VALUES ('P.P', 'peletizado');
INSERT INTO COLOR_AREAS (color, area) VALUES ('P.P Azul', 'peletizado');
INSERT INTO COLOR_AREAS (color, area) VALUES ('P.P Gris', 'peletizado');
INSERT INTO COLOR_AREAS (color, area) VALUES ('P.P Lona', 'peletizado');
INSERT INTO COLOR_AREAS (color, area) VALUES ('P.P Marrón', 'peletizado');
INSERT INTO COLOR_AREAS (color, area) VALUES ('P.P Negro', 'peletizado');
INSERT INTO COLOR_AREAS (color, area) VALUES ('P.P Rojo', 'peletizado');
INSERT INTO COLOR_AREAS (color, area) VALUES ('R Amarillo', 'sellado');
INSERT INTO COLOR_AREAS (color, area) VALUES ('R Amarillo', 'rollo');
INSERT INTO COLOR_AREAS (color, area) VALUES ('R Azul', 'sellado');
INSERT INTO COLOR_AREAS (color, area) VALUES ('R Azul', 'rollo');
INSERT INTO COLOR_AREAS (color, area) VALUES ('R Blanco', 'sellado');
INSERT INTO COLOR_AREAS (color, area) VALUES ('R Blanco', 'rollo');
INSERT INTO COLOR_AREAS (color, area) VALUES ('R Rojo', 'sellado');
INSERT INTO COLOR_AREAS (color, area) VALUES ('R Rojo', 'rollo');
INSERT INTO COLOR_AREAS (color, area) VALUES ('R Verde', 'sellado');
INSERT INTO COLOR_AREAS (color, area) VALUES ('R Verde', 'rollo');
INSERT INTO COLOR_AREAS (color, area) VALUES ('Rojo', 'sellado');
INSERT INTO COLOR_AREAS (color, area) VALUES ('Rojo', 'rollo');
INSERT INTO COLOR_AREAS (color, area) VALUES ('Rojo', 'extrusion');
INSERT INTO COLOR_AREAS (color, area) VALUES ('Rojo', 'peletizado');
INSERT INTO COLOR_AREAS (color, area) VALUES ('Transparente', 'sellado');
INSERT INTO COLOR_AREAS (color, area) VALUES ('Transparente', 'rollo');
INSERT INTO COLOR_AREAS (color, area) VALUES ('Transparente', 'extrusion');
INSERT INTO COLOR_AREAS (color, area) VALUES ('Verde', 'sellado');
INSERT INTO COLOR_AREAS (color, area) VALUES ('Verde', 'rollo');
INSERT INTO COLOR_AREAS (color, area) VALUES ('Verde', 'extrusion');
INSERT INTO COLOR_AREAS (color, area) VALUES ('Verde', 'peletizado');
