-- Operario x Área -- generado por Relaciones > Exportar el 2026-10-02 19:08
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Alejandra', 'sellado');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Alejandro', 'sellado');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Alejandro', 'rollo');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Angie N', 'sellado');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Angie N', 'rollo');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Angie R', 'sellado');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Angie R', 'rollo');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Anthony', 'sellado');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Anthony', 'rollo');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Aponte', 'sellado');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Aponte', 'rollo');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Arianyerli', 'sellado');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Arianyerli', 'rollo');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Armando', 'peletizado');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Arturo', 'peletizado');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Beimar', 'peletizado');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Bibiana', 'sellado');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Brayan', 'sellado');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Brayan', 'rollo');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Camilo', 'sellado');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Camilo', 'rollo');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Cristian', 'sellado');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Cristian', 'rollo');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Danna', 'sellado');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Danna', 'rollo');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Daza', 'sellado');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Daza', 'rollo');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Duglas', 'peletizado');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Gervis', 'peletizado');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Jean Carlos', 'peletizado');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Jhon', 'sellado');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Jhon', 'rollo');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Jose', 'peletizado');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Jose D', 'peletizado');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Jose P', 'peletizado');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Julieth', 'sellado');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Julieth', 'rollo');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Julio', 'sellado');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Julio', 'rollo');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Julio', 'peletizado');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Karen', 'sellado');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Karen', 'rollo');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Leidy', 'sellado');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Liadis', 'sellado');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Liliana', 'sellado');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Liliana', 'rollo');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Lorenzo', 'sellado');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Luis', 'peletizado');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Maibelis', 'sellado');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Maibelis', 'rollo');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Manuel', 'sellado');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Marcilia', 'sellado');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Marcilia', 'rollo');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Marcilia', 'plana');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Mariela', 'sellado');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Mariela', 'rollo');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Marlon', 'peletizado');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Miguel', 'sellado');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Miguel', 'peletizado');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Milenis', 'sellado');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Milenis', 'plana');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Monica', 'sellado');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Monica', 'rollo');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Natalia', 'sellado');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Natalia', 'rollo');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Natalia', 'plana');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Nathaly', 'sellado');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Nathaly', 'rollo');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Nayibe', 'sellado');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Nickool', 'sellado');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Olga', 'sellado');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Olga', 'rollo');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Paola', 'sellado');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Paola', 'rollo');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Raimundo', 'peletizado');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Roibeth', 'peletizado');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Ruben', 'sellado');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Ruben', 'rollo');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Sandra', 'sellado');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Sandra', 'rollo');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Santos', 'sellado');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Sergio C', 'sellado');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Sergio M', 'sellado');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Sergio M', 'rollo');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Yelitza', 'sellado');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Yelitza', 'plana');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Yonathan', 'peletizado');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Yulian', 'sellado');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Yulian', 'rollo');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Yulian', 'plana');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Yuri', 'sellado');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Yuri', 'rollo');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Jean', 'peletizado');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Carlos', 'peletizado');
INSERT INTO OPERARIO_AREAS (operario, area) VALUES ('Ronald', 'peletizado');
