-- Operarios (OPERARIOS) -- generado por Catalogos > Exportar el 2026-09-26 18:58
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Adriana', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Alejandra', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Alejandro', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Andrés', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Angie N', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Angie R', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Anthony', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Aponte', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Arianyerli', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Bibiana', 1, 1);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Brayan', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Briyit', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Camilo', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Cristian', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Danna', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Daza', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Isabel', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Jhon', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Jhon G', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Juan David', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Julieth', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Julio', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Karen', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Leidy', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Liadis', 1, 1);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Liliana', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Liliana T', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Lorenzo', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Maibelis', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Manuel', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Marcilia', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Mariela', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Miguel', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Milenis', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Monica', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Natalia', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Nathaly', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Nayibe', 1, 1);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Nickool', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Olga', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Paola', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Ruben', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Sandra', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Santos', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Sergio C', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Sergio M', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Yelitza', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Yulian', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Yuri', 1, 0);
