-- Operarios (OPERARIOS) -- generado por Catalogos > Exportar el 2026-10-02 23:31
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Adriana', 0, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Alejandra', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Alejandro', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Andrés', 0, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Angie N', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Angie R', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Anthony', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Aponte', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Arianyerli', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Armando', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Arturo', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Beimar', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Bibiana', 1, 1);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Brayan', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Briyit', 0, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Camilo', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Carlos', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Cristian', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Danna', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Daza', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Duglas', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Gervis', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Isabel', 0, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Jean', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Jean Carlos', 0, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Jhon', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Jhon G', 0, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Jose', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Jose D', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Jose P', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Juan David', 0, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Julieth', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Julio', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Karen', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Leidy', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Liadis', 1, 1);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Liliana', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Liliana T', 0, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Lorenzo', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Luis', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Maibelis', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Manuel', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Marcilia', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Mariela', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Marlon', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Miguel', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Milenis', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Monica', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Natalia', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Nathaly', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Nayibe', 1, 1);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Nickool', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Olga', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Paola', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Raimundo', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Roibeth', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Ronald', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Ruben', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Sandra', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Santos', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Sergio C', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Sergio M', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Victor', 0, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Yelitza', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Yonathan', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Yulian', 1, 0);
INSERT INTO OPERARIOS (nombre_operario, estado, es_supervisor) VALUES ('Yuri', 1, 0);
