-- Referencias Especiales (REFERENCIAS_ESP) -- generado por Catalogos > Exportar el 2026-09-25 17:31
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('1,5K ESP', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('100x1,5', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('100x100', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('10K ESP', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('15K ESP', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('16x20', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('16x24', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('18+4+4', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('18x24', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('18x40', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('19x25', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('20K ESP', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('20x39', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('21x28', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('22x28', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('22x30', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('23x40', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('23x44', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('24+4+4', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('24+4+4x1,05', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('24+4+4x1,2', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('24+7+7', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('24,5+7+7', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('24,5+7+7x1,8', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('24x1', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('24x31', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('24x32', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('24x32 Negro', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('24x32 Rojo', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('24x32 Verde', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('24x34', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('25K ESP', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('25x0,72', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('25x31', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('26+4+4', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('26+4+4x1,2', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('26+5+5x1,6', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('26x1,5', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('26x35', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('26x36', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('28x1,8', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('28x40', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('2K ESP', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('30K ESP', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('30x0,95', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('30x40', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('31x40', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('32+14+14', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('32+14+14x3,6', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('32x2', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('32x24', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('32x44', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('39x50', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('3K ESP', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('40x55', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('45+8+8x1,6', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('45x45', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('48x0,83', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('50+10+10x0,85', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('50+7,5+7,5x0,62', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('50K ESP', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('50x80', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('50x88', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('5K ESP', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('60+10+10x0,8', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('60+10+10x0,85', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('60x0,87', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('64+13+13', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('65+15+15x0,8', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('65x0,98', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('65x1,1', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('65x1,2', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('65x100', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('65x88', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('65x90', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('70x0,94', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('70x1', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('70x104', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('70x90', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('72x3,7', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('80x1,10', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('88x1,18', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('88x1,2', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('90x1,10', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('90x1,20', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('90x1,5', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('95x1,10', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('Extra Jumbo', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('Jumbo', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('King Kong', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('Mediana', 1);
INSERT INTO REFERENCIAS_ESP (nombre_referencia_esp, estado) VALUES ('N N', 1);
